name: altspace
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4a0a1'
    - '#7d7b7e'
    - '#424244'
    - '#d0c7c8'
    - '#2c2b30'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
